version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
      nodejs: 12.x
  pre_build:
    commands:
      - npm install --global yarn
      - echo $(yarn --version)
      - yarn install
      - pip install awscli
  build:
    commands:
      - yarn build
      - aws s3 sync ./out s3://$S3_BUCKET_NAME/ --quiet
