name: Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-acces-key-id: ${{AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - name: Cache dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{runner.os}}-node-
          
      - name: Generate files
        run: yarn build
      
      - name: Upload files to S3
        env:
          S3_BUCKET_NAME: ${{ S3_BUCKET_NAME }}
        run: aws s3 sync ./out s3://$S3_BUCKET_NAME/ --quiet
